plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/exec":
      verifyConditions: "./verify.sh"
      prepareCmd: "echo 'prepareCmd'"
      publishCmd: "echo 'publishCmd'"
      successCmd: "echo 'successCmd'"
      failCmd: "echo 'failCmd'"
  - "@semantic-release/github"
  - "@semantic-release/git":
      assets:
        - pom.xml
      message: "chore(release): bump ${nextRelease.version}"

branches:
  - "master"

