plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: 'echo "NEXT_VERSION=${nextRelease.version}" >> build.env'
      publishCmd: "echo 'prepareCmd ${nextRelease.version}'"
      prepareCmd: "echo 'prepareCmd ${nextRelease.version}'"
    #- verifyReleaseCmd: 'mvn versions:set -DnewVersion="${nextRelease.version}" && echo "NEXT_VERSION=${nextRelease.version}" >> build.env'
  - "@semantic-release/github"
  - -  "@semantic-release/git"
    - assets:
        - pom.xml
      message: "chore(release): bump ${nextRelease.version}"

branches:
  - "master"
